### PR TITLE
bug:DOMTokenList error

### LINKED ISSUE #223: [BUG] Fix DOMTokenList error caused by theme names containing spaces
### Current behaviour
When running npm run dev, the application throws a DOMTokenList error in the browser console:
The error occurs in src/app/layout.tsx at line 37 where the ThemeProvider component is used. This prevents the application from starting properly and breaks theme switching functionality.

### Steps to reproduce
1. Clone the repository
2. Run npm install to install dependencies
3. Run npm run dev to start the development server
4. Open browser console
5. See the DOMTokenList error

### Expected outcome
The application should start without any DOMTokenList errors, and theme switching should work correctly. The ThemeProvider should only use valid CSS class tokens (without spaces or special characters).

### Screenshots / Recordings

Image
---

### PR DESCRIPTION
**Pull request by kunal-10-cloud**
Fixes: #223 

## Description
This PR fixes the DOMTokenList error that occurs when running npm run dev. The error was caused by theme names containing spaces (like "Default Theme") being passed to the next-themes library, which tries to add them as CSS class tokens. CSS class tokens cannot contain spaces or special characters, causing the application to fail to start properly.

## Changes Made
[x] Added custom storageKey="devui-theme" to ThemeProvider in src/app/layout.tsx
[x] Implemented theme name validation and cleanup logic in src/components/ui/ThemeColorPicker.tsx
[x] Added automatic removal of invalid theme names from localStorage on component mount
[x] Enhanced theme name validation using regex /[^a-zA-Z0-9-_]/g to remove invalid characters
[x] Added cleanup for both custom and next-themes localStorage keys

## Screenshots or GIFs (if applicable)
Before: 
Screenshot 2025-10-18 at 2 47 21 PM

After: 
Screenshot 2025-10-18 at 2 46 59 PM

### CODE REVIEW

**Comment by kunal-10-cloud** [comment]
@fahimahammed could you please take a look on this issue and the pr and suggest me any changes required

File: src/app/layout.tsx [hunk 1]
```diff
@@ -34,7 +34,7 @@ export default function RootLayout({
         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       >
         {/* ✅ Wrap everything in ThemeProvider */}
-        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
+        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem storageKey="devui-theme">
```
Comment (fahimahammed) [inline src/app/layout.tsx:39]: Please resolve merge conflict

**Review by fahimahammed — CHANGES_REQUESTED** [review]
resolve merge conflict

File: src/app/layout.tsx (hunk 1 above)
Comment (kunal-10-cloud) [reply src/app/layout.tsx:39]: i have resolved the conflict now please take a look on the pr and merge it.

File: src/app/layout.tsx [hunk 2]
```diff
@@ -35,11 +35,11 @@ export default function RootLayout({
       <body
         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       >
-        {/*  Wrap everything in ThemeProvider */}
-        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
+        {/* ✅ Wrap everything in ThemeProvider */}
```
Comment (fahimahammed) [inline src/app/layout.tsx:38]: approved. thank you

**Review by fahimahammed — APPROVED** [review]
thank you
